version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '8080:8080'
    links:
     - redis:redis
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
  redis:
    image: "redis:6.2-alpine"
    restart: always
    ports:
      - '5379:6379'
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local