FROM node:lts-alpine AS node-modules-builder
LABEL maintainer="ORA Group"
WORKDIR /usr/src/app
RUN apk update && apk add python3 g++ make && rm -rf /var/cache/apk/*
COPY . ./
# Install backend dependencies
RUN npm ci
# Transpile
RUN npm run build

FROM node:lts-alpine
WORKDIR /usr/src/app
EXPOSE 8080
ENV PORT 8080
RUN apk update && apk add tini && rm -rf /var/cache/apk/*
COPY --from=node-modules-builder /usr/src/app ./
ENTRYPOINT ["tini", "--"]
CMD ["npm", "run", "start:prod"]